server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: tycoon
    
  datasource:
    url: ${MARIADB_URL}
    username: ${MARIADB_USERNAME}
    password: ${MARIADB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 17
    locations: classpath:db/migration
    encoding: UTF-8
    validate-on-migrate: false
    clean-disabled: false
    out-of-order: false
    table: flyway_schema_history
    create-schemas: true
    schemas: factory-tycoon

jwt:
  secret: ${JWT_SECRET_KEY}
  access-ttl-ms: ${JWT_ACCESS_TTL_MS}
  refresh-ttl-ms: ${JWT_REFRESH_TTL_MS}