server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: tycoon
    
  datasource:
    url: jdbc:mysql://175.114.229.158:3306/factory-tycoon2
    username: root
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  data:
    redis:
      host: 175.114.229.158
      port: 6379

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration  # TODO: 마이그레이션 스크립트 위치 변경 가능
    encoding: UTF-8
    validate-on-migrate: true
    clean-disabled: true
    out-of-order: false
    table: flyway_schema_history

jwt:
  secret: your-secret-key-change-this-in-production-min-256-bits
  access-ttl-ms: 3600000
  refresh-ttl-ms: 86400000

opensearch:
  endpoint: https://vpc-factory-tycoon-search-hfbepbqmh7clcs6u73ou53d7ta.ap-northeast-2.es.amazonaws.com
  region: ap-northeast-2

