name: database
services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.11
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: pass
      MARIADB_DATABASE: factory-tycoon
      MARIADB_USER: user
      MARIADB_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mariadb/conf.d:/etc/mysql/conf.d:ro
      # - ./mariadb/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p$$MARIADB_ROOT_PASSWORD --silent"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    networks:
      - db_network

  mongodb:
    container_name: mongodb
    image: mongo:8.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: factory-tycoon
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
      - ./mongodb/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand('ping').ok"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - db_network

  redis:
    container_name: redis
    image: redis:7.4
    restart: always
    command: redis-server --requirepass pass
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "pass", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - db_network

volumes:
  mariadb_data:
    driver: local
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  redis_data:
    driver: local

networks:
  db_network:
    driver: bridge
